"""
Script Executor module
------------------
Safely executes Python scripts generated by the LLM
"""

import os
import pandas as pd
import numpy as np
import json
import re
from typing import Tuple, List, Dict, Any, Optional, Hashable
from src.controller.security_manager import SecurityManager
from src.controller.script_manager import ScriptManager
from src.controller.file_manager import FileManager
from src.controller.script_tester import ScriptTester
from src.llm.token_manager import token_manager

class ScriptExecutor:
    """
    Executes Python scripts generated by the LLM on spreadsheet data
    """
    
    def __init__(self, script_dir: Optional[str] = None):
        """
        Initialize the script executor
        
        Args:
            script_dir: Optional directory path for saving scripts
        """
        self.security_manager = SecurityManager()
        self.script_dir = script_dir or os.path.join('src', 'script')
        self.script_manager = ScriptManager(self.script_dir)
        self.script_tester = ScriptTester()
    
    def refresh_spreadsheet_structure(self, session_id: str) -> pd.DataFrame:
        """
        Refresh and get the current spreadsheet structure from the session.
        This ensures we're working with the most up-to-date data including any
        manual changes made by the user.
        
        Args:
            session_id: The session ID to get data from
            
        Returns:
            pd.DataFrame: The current spreadsheet data
        """
        from src.model.session_manager import SessionManager
        
        # Get the session manager instance
        # Note: In a real implementation, this would be injected as a dependency
        # For now, we'll assume it's accessible through a global instance or similar
        try:
            # Import here to avoid circular dependencies
            from src.controller.spreadsheet_controller import SpreadsheetController
            
            # We need to get the session manager somehow
            # This is a design consideration - ideally it should be injected
            print("🔄 Refreshing spreadsheet structure before script execution...")
            
            # For now, we'll return the original DataFrame
            # In a proper implementation, this method would be called from the controller
            # with the updated DataFrame passed as parameter
            print("⚠️ Note: Spreadsheet structure refresh should be called from controller level")
            return None
            
        except ImportError:
            print("⚠️ Warning: Cannot refresh spreadsheet structure - missing dependencies")
            return None
    
    def execute_script(self, script: str, spreadsheet_df: pd.DataFrame, file_manager: Optional[FileManager] = None, session_id: Optional[str] = None) -> Tuple[pd.DataFrame, List[List[int]]]:
        """
        Execute a Python script on spreadsheet data

        Args:
            script: The Python script generated by LLM
            spreadsheet_df: The pandas DataFrame containing spreadsheet data
            file_manager: Optional FileManager to save script for reference
            session_id: Optional session ID for structure refresh

        Returns:
            Tuple[pd.DataFrame, List[List[int]]]: Modified DataFrame and list of modified cells
        """
        print(f"\n{'='*60}")
        print("🔧 SCRIPT EXECUTION STARTING")
        print(f"{'='*60}")
        print("-" * 60)
        
        # Step 1: Refresh spreadsheet structure if session_id is provided
        if session_id:
            print("🔄 Checking for updated spreadsheet structure...")
            # Note: In practice, the controller should pass the most current DataFrame
            print(f"📊 Using provided DataFrame: {spreadsheet_df.shape[0]} rows, {spreadsheet_df.shape[1]} columns")
        
        # Step 2: Display current structure for debugging
        print(f"📊 Current spreadsheet structure:")
        print(f"   - Shape: {spreadsheet_df.shape}")
        print(f"   - Columns: {list(spreadsheet_df.columns)}")
        if len(spreadsheet_df) > 0:
            print(f"   - Sample data (first row): {spreadsheet_df.iloc[0].tolist()}")
        
        # Step 3: Test and fix script using script tester and fixer pipeline
        print("🔧 Testing script with ScriptTester...")
        is_valid, error_message, fixed_script = self.script_tester.test_script(script, spreadsheet_df.head(5))
        
        if not is_valid:
            print(f"⚠️  Script validation failed: {error_message}")
            if fixed_script:
                print("🔧 ScriptTester provided a fix, using it...")
                script = fixed_script
                # Re-test the fixed script
                is_valid, error_message, _ = self.script_tester.test_script(script, spreadsheet_df.head(5))
                if is_valid:
                    print("✅ Fixed script passes validation")
                else:
                    print(f"⚠️  Fixed script still has issues: {error_message}")
                    # Try ScriptFixer for more advanced fixing
                    print("🔧 Using ScriptFixer for advanced error correction...")
                    from src.controller.script_fixer import ScriptFixer
                    script_fixer = ScriptFixer()
                    
                    # Create a dummy command for context
                    dummy_command = "User command requiring script execution"
                    fixed_df, modified_cells, success = script_fixer.fix_and_execute_script(
                        script, spreadsheet_df, dummy_command, self.security_manager
                    )
                    
                    if success:
                        print("✅ ScriptFixer successfully executed the script")
                        return fixed_df, modified_cells
                    else:
                        print("❌ ScriptFixer could not fix the script")
                        raise ValueError(f"Script could not be fixed: {error_message}")
            else:
                print("❌ No automatic fix available from ScriptTester")
                # Try ScriptFixer for advanced fixing
                print("🔧 Using ScriptFixer for advanced error correction...")
                from src.controller.script_fixer import ScriptFixer
                script_fixer = ScriptFixer()
                
                # Create a dummy command for context
                dummy_command = "User command requiring script execution"
                fixed_df, modified_cells, success = script_fixer.fix_and_execute_script(
                    script, spreadsheet_df, dummy_command, self.security_manager
                )
                
                if success:
                    print("✅ ScriptFixer successfully executed the script")
                    return fixed_df, modified_cells
                else:
                    print("❌ ScriptFixer could not fix the script")
                    raise ValueError(f"Script validation and fixing failed: {error_message}")
        
        # Validate script for security (after fixing)
        if not self.security_manager.validate_script(script):
            error_msg = "Script validation failed due to security concerns. See server logs for details."
            print(f"❌ Security validation failed: {error_msg}")
            raise ValueError(error_msg)
        
        print("✅ Script validation passed")
        
        # --- UNIVERSALITY PATCH: Validate script universality before execution ---
        is_universal = self._validate_script_universality(script)
        if not is_universal:
            print("🔧 Patching script to follow universal transformation patterns")
            
        # Convert hardcoded iloc operations to universal patterns (always apply for safety)
        script = self._preprocess_script_for_universal_execution(script, spreadsheet_df)
        
        # Create a unique ID for this script
        import uuid
        script_id = str(uuid.uuid4())[:8]
        
        # Save script to src/script directory
        script_dir = self.script_dir
        os.makedirs(script_dir, exist_ok=True)
        script_path = os.path.join(script_dir, f"script_{script_id}.py")
        with open(script_path, 'w', encoding='utf-8') as f:
            f.write(script)
            
        print(f"💾 Script saved: {script_id}")
            
        # Save script metadata to json directory for reference if file_manager is provided
        if file_manager:
            file_manager.save_json_data({
                'script': script,
                'script_id': script_id,
                'timestamp': str(pd.Timestamp.now()),
                'columns': spreadsheet_df.columns.tolist(),
                'rows': len(spreadsheet_df)
            }, f"script_{script_id}")
            print(f"📊 Script metadata saved")
        
        # Track original data for determining modifications
        orig_columns = set(spreadsheet_df.columns)
        filled_df: pd.DataFrame = spreadsheet_df.copy().fillna(value=np.nan)
        data_dict: Dict[Hashable, Any] = filled_df.to_dict()
        orig_values = {str(k): v for k, v in data_dict.items()}
        
        print(f"📊 Original data: {spreadsheet_df.shape[0]} rows, {spreadsheet_df.shape[1]} columns")
        
        # Create a sandbox environment
        sandbox_globals = self._create_sandbox(spreadsheet_df)
        
        try:
            print("⚙️  Executing script...")
            
            # Execute script
            exec(script, sandbox_globals)

            # Get the modified dataframe
            modified_df = sandbox_globals.get('df', spreadsheet_df)

            # Reset the index to ensure consistent row numbering
            modified_df = modified_df.reset_index(drop=True)

            # Find modified cells
            modified_cells = self._find_modified_cells(
                orig_df=spreadsheet_df, 
                orig_columns=orig_columns,
                orig_values=orig_values, 
                new_df=modified_df
            )

            print(f"✅ Script executed successfully - {len(modified_cells)} cells modified")
            
            # Enhanced validation for dataset completeness
            if len(spreadsheet_df) > 100:  # Only for larger datasets
                max_modified_row = max(cell[0] for cell in modified_cells) if modified_cells else -1
                coverage_percentage = ((max_modified_row + 1) / len(spreadsheet_df)) * 100 if modified_cells else 0
                
                if coverage_percentage < 10:  # Less than 10% coverage
                    print(f"⚠️  WARNING: Transformation only covers {coverage_percentage:.1f}% of the dataset")
                    print("🔧 Attempting to extend transformation pattern...")
                    modified_df, modified_cells = self._extend_transformation_to_full_dataset(
                        modified_df, modified_cells, len(spreadsheet_df)
                    )
                    print(f"✅ Extended transformation applied - now {len(modified_cells)} cells modified")
            
            # Validate result completeness
            self._validate_result_completeness(spreadsheet_df, modified_df)

            return modified_df, modified_cells
        except Exception as e:
            error_msg = str(e)
            print(f"❌ Script execution failed: {error_msg}")
            
            # --- ENHANCED PATCH: If error is 'iloc cannot enlarge its target object', analyze and expand DataFrame ---
            if 'iloc cannot enlarge its target object' in error_msg:
                print("🔧 Attempting enhanced DataFrame patch for iloc enlargement error...")
                
                # Analyze the script to determine required DataFrame size
                max_row_needed, max_col_needed = self._analyze_script_size_requirements(script)
                
                # Expand DataFrame based on analysis
                patched_df = spreadsheet_df.copy()
                current_rows, current_cols = patched_df.shape
                
                # Ensure we have enough rows
                if max_row_needed >= current_rows:
                    rows_to_add = max_row_needed - current_rows + 10  # Add some buffer
                    print(f"🔧 Adding {rows_to_add} rows (current: {current_rows}, needed: {max_row_needed})")
                    for _ in range(rows_to_add):
                        patched_df.loc[len(patched_df)] = [None] * len(patched_df.columns)
                
                # Ensure we have enough columns
                if max_col_needed >= current_cols:
                    cols_to_add = max_col_needed - current_cols + 5  # Add some buffer
                    print(f"🔧 Adding {cols_to_add} columns (current: {current_cols}, needed: {max_col_needed})")
                    for i in range(cols_to_add):
                        patched_df[f'_auto_col_{current_cols + i}'] = None
                
                try:
                    # Apply preprocessing to convert hardcoded operations
                    processed_script = self._preprocess_script_for_universal_execution(script, patched_df)
                    
                    sandbox_globals = self._create_sandbox(patched_df)
                    exec(processed_script, sandbox_globals)
                    modified_df = sandbox_globals.get('df', patched_df)
                    modified_df = modified_df.reset_index(drop=True)
                    
                    # Trim back to original size if expansion was only for error prevention
                    if modified_df.shape[0] > spreadsheet_df.shape[0]:
                        # Check if the extra rows contain meaningful data
                        extra_rows = modified_df.iloc[spreadsheet_df.shape[0]:].copy()
                        if extra_rows.isna().all().all() or (extra_rows == '').all().all():
                            # Extra rows are empty, trim them
                            modified_df = modified_df.iloc[:spreadsheet_df.shape[0]].copy()
                            print("🔧 Trimmed empty extra rows after successful execution")
                    
                    modified_cells = self._find_modified_cells(
                        orig_df=spreadsheet_df, 
                        orig_columns=orig_columns,
                        orig_values=orig_values, 
                        new_df=modified_df
                    )
                    print("✅ Enhanced patched execution successful")
                    return modified_df, modified_cells
                except Exception as e2:
                    print(f"❌ Enhanced patched execution failed: {e2}")
                    raise RuntimeError(f"Script execution failed after enhanced patch: {e2}")
            # Return the original DataFrame without modifications instead of adding error column
            raise RuntimeError(f"Script execution failed: {error_msg}")
    
    def validate_script_safety(self, script: str) -> bool:
        """
        Validate that a script is safe to execute

        Args:
            script: The Python script to validate

        Returns:
            bool: True if the script is safe, False otherwise
        """
        return self.security_manager.validate_script(script)
    
    def _create_sandbox(self, df: pd.DataFrame) -> Dict[str, Any]:
        """
        Create a sandbox environment for script execution

        Args:
            df: The pandas DataFrame to operate on

        Returns:
            Dict[str, Any]: Dictionary of global variables for the sandbox
        """
        # Create a copy of the dataframe to avoid modifying the original
        sandbox_df = df.copy()
        
        # Define allowed modules and functions
        sandbox: Dict[str, Any] = {
            'df': sandbox_df,
            'pd': pd,
            'np': np,
            'print': print
        }
        
        return sandbox
    
    def _find_modified_cells(self, orig_df: pd.DataFrame, orig_columns: set[str], orig_values: Dict[str, Any], new_df: pd.DataFrame) -> List[List[int]]:
        """
        Find cells that were modified by the script

        Args:
            orig_df: Original DataFrame
            orig_columns: Set of original column names
            orig_values: Dict of original values
            new_df: Modified DataFrame

        Returns:
            List[List[int]]: List of [row, col] coordinates for modified cells
        """
        modified_cells: List[List[int]] = []
        
        # Check for new columns
        new_columns = set(new_df.columns) - orig_columns
        for col_name in new_columns:
            col_idx = list(new_df.columns).index(col_name)
            for row_idx in range(len(new_df)):
                modified_cells.append([row_idx, col_idx])
        
        # Check for modified values in existing columns
        for col_name in orig_columns:
            if col_name in new_df.columns:
                col_idx = list(new_df.columns).index(col_name)
                orig_col_idx = list(orig_df.columns).index(col_name)
                
                for row_idx in range(min(len(orig_df), len(new_df))):
                    # Check for equality considering NaN values
                    orig_val: Any = orig_df.iat[row_idx, orig_col_idx]
                    new_val: Any = new_df.iat[row_idx, col_idx]
                    
                    if pd.isna(orig_val) and pd.isna(new_val):
                        continue  # Both NaN, not modified
                    elif pd.isna(orig_val) or pd.isna(new_val):
                        # One is NaN and the other isn't, they're different
                        modified_cells.append([row_idx, col_idx])
                    elif orig_val != new_val:
                        # Both are non-NaN but have different values
                        modified_cells.append([row_idx, col_idx])
        
        return modified_cells
    
    # PLACEHOLDER: Schema generation methods removed
    # The following methods were removed as part of schema functionality cleanup:
    # - generate_schema_from_df()
    # - generate_transformation_script()
    # New implementation will replace these with different logic.

    def execute_universal_algorithm(self, script: str, spreadsheet_df: pd.DataFrame, file_manager: Optional[FileManager] = None) -> Tuple[pd.DataFrame, List[List[int]]]:
        """
        Execute a universal algorithm script on spreadsheet data with error handling and retry
        
        Args:
            script: The universal algorithm script generated by LLM
            spreadsheet_df: The pandas DataFrame containing spreadsheet data
            file_manager: Optional FileManager to save script for reference
            
        Returns:
            Tuple[pd.DataFrame, List[List[int]]]: Modified DataFrame and list of modified cells
        """
        print(f"\n{'='*60}")
        print("🚀 UNIVERSAL ALGORITHM EXECUTION STARTING")
        print(f"{'='*60}")
        
        try:
            result = self.execute_script(script, spreadsheet_df.copy(), file_manager)
            print(f"✅ Universal algorithm execution successful")
            return result
            
        except Exception as e:
            error_msg = str(e)
            print(f"❌ Universal algorithm execution failed: {error_msg}")
            # Store the error for potential retry
            self._last_error = error_msg
            raise e

    def execute_universal_algorithm_with_validation(self, script: str, spreadsheet_df: pd.DataFrame, file_manager: Optional[FileManager] = None) -> Tuple[pd.DataFrame, List[List[int]]]:
        """
        Execute a universal algorithm script with enhanced validation to ensure full dataset processing
        
        Args:
            script: The universal algorithm script generated by LLM
            spreadsheet_df: The pandas DataFrame containing spreadsheet data
            file_manager: Optional FileManager to save script for reference
            
        Returns:
            Tuple[pd.DataFrame, List[List[int]]]: Modified DataFrame and list of modified cells
            
        Raises:
            RuntimeError: If the algorithm appears to only process partial data
        """
        print(f"\n{'='*60}")
        print("UNIVERSAL ALGORITHM EXECUTION WITH VALIDATION STARTING")
        print(f"{'='*60}")
        
        original_row_count = len(spreadsheet_df)
        original_col_count = len(spreadsheet_df.columns)
        
        print(f"📊 Original dataset: {original_row_count} rows, {original_col_count} columns")
        
        try:
            # Execute the script
            result_df, modified_cells = self.execute_script(script, spreadsheet_df.copy(), file_manager)
            
            # Validate that the algorithm processed the full dataset
            result_row_count = len(result_df)
            result_col_count = len(result_df.columns)
            
            print(f"📈 Result dataset: {result_row_count} rows, {result_col_count} columns")
            
            # Check if the algorithm appears to have only processed a subset of data
            if result_row_count < original_row_count * 0.9:  # If result has less than 90% of original rows
                error_msg = (
                    f"VALIDATION FAILED: Algorithm appears to have only processed {result_row_count} rows "
                    f"out of {original_row_count} original rows. This suggests the algorithm is not "
                    f"processing the entire dataset as required. The algorithm should work on ALL rows "
                    f"in the DataFrame, not just a subset."
                )
                print(f"❌ VALIDATION FAILED: {error_msg}")
                raise RuntimeError(error_msg)
            
            # Enhanced validation: check if modifications seem limited to first few rows only
            if len(modified_cells) > 0:
                max_modified_row = max(cell[0] for cell in modified_cells)
                rows_with_modifications = set(cell[0] for cell in modified_cells)
                
                # Check if algorithm only processed a tiny subset of rows
                if max_modified_row < min(50, original_row_count * 0.1):  # If modifications only in first 50 rows or less than 10% of data
                    if original_row_count > 100:  # Only flag this for larger datasets
                        print(f"⚠️  WARNING: Algorithm only processed rows 0-{max_modified_row} out of {original_row_count} total rows.")
                        print("🔧 Attempting to extend transformation pattern to full dataset...")
                        
                        # Try to extend the transformation to the full dataset
                        result_df, modified_cells = self._extend_transformation_to_full_dataset(
                            result_df, modified_cells, original_row_count
                        )
                        
                        # Re-check after extension
                        max_modified_row = max(cell[0] for cell in modified_cells) if modified_cells else 0
                        rows_with_modifications = set(cell[0] for cell in modified_cells)
                        
                        if max_modified_row < original_row_count * 0.5:  # Still problematic
                            error_msg = (
                                f"VALIDATION FAILED: Even after pattern extension, algorithm only processed rows 0-{max_modified_row} "
                                f"out of {original_row_count} total rows ({len(rows_with_modifications)} modified rows). "
                                f"This indicates the algorithm is fundamentally flawed and not universal."
                            )
                            print(f"❌ {error_msg}")
                            raise RuntimeError(error_msg)
                        else:
                            print("✅ Pattern extension successful - transformation now covers more of the dataset")
                
                # More strict check: if we have a large dataset but very few rows modified
                if original_row_count > 1000 and len(rows_with_modifications) < original_row_count * 0.05:
                    print(f"⚠️  WARNING: Only {len(rows_with_modifications)} out of {original_row_count} rows were modified.")
                    print("🔧 Attempting to extend transformation pattern to full dataset...")
                    
                    # Try to extend the transformation to the full dataset
                    result_df, modified_cells = self._extend_transformation_to_full_dataset(
                        result_df, modified_cells, original_row_count
                    )
                    
                    # Re-check after extension
                    rows_with_modifications = set(cell[0] for cell in modified_cells)
                    
                    if len(rows_with_modifications) < original_row_count * 0.1:  # Still too few
                        error_msg = (
                            f"VALIDATION FAILED: Even after pattern extension, only {len(rows_with_modifications)} out of {original_row_count} rows "
                            f"were modified ({(len(rows_with_modifications)/original_row_count)*100:.1f}%). "
                            f"For a dataset this large, the algorithm should process most/all rows."
                        )
                        print(f"❌ {error_msg}")
                        raise RuntimeError(error_msg)
                    else:
                        print("✅ Pattern extension successful - more rows now processed")
                
                # Check for empty cells in the result - should not exist if algorithm is complete
                empty_cell_count = result_df.isna().sum().sum() + (result_df == "").sum().sum()
                total_cells = result_df.shape[0] * result_df.shape[1]
                
                if empty_cell_count > total_cells * 0.8:  # If more than 80% of cells are empty
                    error_msg = (
                        f"VALIDATION FAILED: Result contains {empty_cell_count} empty cells "
                        f"out of {total_cells} total cells ({(empty_cell_count/total_cells)*100:.1f}% empty). "
                        f"A complete universal algorithm should populate all cells with appropriate data."
                    )
                    print(f"❌ {error_msg}")
                    raise RuntimeError(error_msg)
                
                if max_modified_row < original_row_count * 0.3:  # If modifications in less than 30% of data
                    warning_msg = (
                        f"⚠️  WARNING: Modifications appear limited to rows 0-{max_modified_row} "
                        f"out of {original_row_count} total rows. Algorithm may not be processing entire dataset."
                    )
                    print(f"{warning_msg}")
            else:
                # No modifications at all - this is definitely wrong
                error_msg = (
                    f"VALIDATION FAILED: No cells were modified in the transformation. "
                    f"This suggests the algorithm failed to process any data."
                )
                print(f"❌ {error_msg}")
                raise RuntimeError(error_msg)
            
            # Additional check: ensure no large blocks of unchanged data remain
            if original_row_count > 20:
                # Check if the last 25% of rows are completely unchanged
                quarter_point = int(original_row_count * 0.75)
                last_quarter_modified = any(cell[0] >= quarter_point for cell in modified_cells)
                
                if not last_quarter_modified:
                    print(f"⚠️  WARNING: No modifications in last 25% of dataset - extending pattern...")
                    result_df, modified_cells = self._extend_transformation_to_full_dataset(
                        result_df, modified_cells, original_row_count
                    )
                    
                    # Re-check after extension
                    last_quarter_modified = any(cell[0] >= quarter_point for cell in modified_cells)
                    
                    if not last_quarter_modified:
                        error_msg = (
                            f"VALIDATION FAILED: Even after pattern extension, no modifications detected in the last 25% of the dataset "
                            f"(rows {quarter_point}-{original_row_count-1}). This suggests the algorithm "
                            f"cannot be properly extended to process the entire dataset."
                        )
                        print(f"❌ {error_msg}")
                        raise RuntimeError(error_msg)
                    else:
                        print("✅ Pattern extension successful - last quarter now has modifications")
            
            # --- VALIDATION PATCH: Check result completeness and detect incomplete transformations ---
            self._validate_result_completeness(spreadsheet_df, result_df)
            
            print(f"✅ Algorithm validation successful: processed {result_row_count} rows")
            
            # --- POST-PROCESSING PATCH: Extend transformations to cover the entire dataset ---
            extended_df, all_modified_cells = self._extend_transformation_to_full_dataset(result_df, modified_cells, original_row_count)
            
            print(f"✅ Post-processing complete: extended transformations to cover entire dataset")
            return extended_df, all_modified_cells
            
        except Exception as e:
            error_msg = str(e)
            print(f"Algorithm execution/validation failed: {error_msg}")
            # Store the error for potential retry
            self._last_error = error_msg
            raise e

    def get_last_execution_error(self) -> str:
        """Get the last execution error for retry purposes"""
        return getattr(self, '_last_error', '')

    def execute_simple_script(self, script: str, spreadsheet_df: pd.DataFrame, command: str, file_manager: Optional[FileManager] = None, session_id: Optional[str] = None) -> Tuple[pd.DataFrame, List[List[int]]]:
        """
        Execute a simple Python script (without universality transformations) with error handling

        Args:
            script: The Python script to execute
            spreadsheet_df: The pandas DataFrame containing spreadsheet data
            command: The original user command
            file_manager: Optional FileManager to save script for reference
            session_id: Optional session ID for structure tracking

        Returns:
            Tuple[pd.DataFrame, List[List[int]]]: Modified DataFrame and list of modified cells
        """
        print(f"\n{'='*60}")
        print("🔧 SIMPLE SCRIPT EXECUTION STARTING")
        print(f"{'='*60}")
        print(f"Original command: {command}")
        print("-" * 60)

        # Step 1: Refresh spreadsheet structure if session_id is provided
        if session_id:
            print("🔄 Checking for updated spreadsheet structure...")
            # Note: In practice, the controller should pass the most current DataFrame
            print(f"📊 Using provided DataFrame: {spreadsheet_df.shape[0]} rows, {spreadsheet_df.shape[1]} columns")
        
        # Step 2: Display current structure for debugging
        print(f"📊 Current spreadsheet structure:")
        print(f"   - Shape: {spreadsheet_df.shape}")
        print(f"   - Columns: {list(spreadsheet_df.columns)}")
        if len(spreadsheet_df) > 0:
            print(f"   - Sample data (first row): {spreadsheet_df.iloc[0].tolist()}")
        
        # Step 3: Execute script in sandbox with comprehensive error handling
        print("\n🧪 Testing script in sandbox environment...")
        from src.controller.script_fixer import ScriptFixer
        script_fixer = ScriptFixer()
        
        # Use script_fixer to handle the entire error correction pipeline
        modified_df, modified_cells, success = script_fixer.fix_and_execute_script(
            script, spreadsheet_df.copy(), command, self.security_manager
        )
        
        if not success:
            error_msg = "Script execution failed after comprehensive error correction attempts. See server logs for details."
            print(f"❌ Final execution failed: {error_msg}")
            
            # In case of failure, raise an exception instead of modifying the DataFrame
            raise RuntimeError(error_msg)
        
        # At the end of execution, print Gemini token usage if available
        self._print_gemini_token_usage()
        
        return modified_df, modified_cells

    def _print_gemini_token_usage(self):
        """
        Print Gemini token usage summary if available.
        This method delegates to the global token_manager.
        """
        token_manager.print_token_usage()

    def set_gemini_token_usage(self, token_usage: dict):
        """
        Set Gemini token usage stats for reporting.
        This method delegates to the global token_manager.
        
        Args:
            token_usage: Dict with token usage details
        """
        token_manager.set_token_usage(token_usage)

    def _preprocess_script_for_universal_execution(self, script: str, df: pd.DataFrame) -> str:
        """
        Preprocess the script to convert hardcoded iloc operations to universal patterns
        
        Args:
            script: The original script
            df: The DataFrame to process
            
        Returns:
            str: Preprocessed script with universal patterns
        """
        lines = script.split('\n')
        processed_lines = []
        
        # Track patterns that suggest hardcoded row operations
        hardcoded_iloc_pattern = re.compile(r'\.iloc\[(\d+),\s*(\d+)\]\s*=\s*(.+)')
        
        iloc_operations = []
        
        for line in lines:
            # Check for hardcoded iloc operations
            match = hardcoded_iloc_pattern.search(line)
            if match:
                row_idx = int(match.group(1))
                col_idx = int(match.group(2))
                value = match.group(3)
                iloc_operations.append((row_idx, col_idx, value.strip()))
                # Skip this line - we'll replace it with universal operations
                continue
            else:
                processed_lines.append(line)
        
        if iloc_operations:
            print(f"🔧 Detected {len(iloc_operations)} hardcoded iloc operations - converting to universal patterns")
            
            # Group operations by column to create efficient vectorized operations
            col_operations = {}
            for row_idx, col_idx, value in iloc_operations:
                if col_idx not in col_operations:
                    col_operations[col_idx] = []
                col_operations[col_idx].append((row_idx, value))
            
            # Generate universal replacement code
            universal_code = [
                "",
                "# Auto-generated universal transformations (converted from hardcoded iloc operations)",
                f"# Ensure DataFrame has enough rows and columns",
                f"required_rows = {max(op[0] for op in iloc_operations) + 1}",
                f"required_cols = {max(op[1] for op in iloc_operations) + 1}",
                f"if len(df) < required_rows:",
                f"    # Add missing rows with empty values",
                f"    for _ in range(required_rows - len(df)):",
                f"        df.loc[len(df)] = [None] * len(df.columns)",
                f"if len(df.columns) < required_cols:",
                f"    # Add missing columns",
                f"    for i in range(len(df.columns), required_cols):",
                f"        df[f'col_{{i}}'] = None",
                ""
            ]
            
            # Convert column operations to universal patterns
            for col_idx, operations in col_operations.items():
                # Check if all operations in this column use the same value
                values = [op[1] for op in operations]
                unique_values = list(set(values))
                
                if len(unique_values) == 1:
                    # All same value - use vectorized assignment for entire column
                    value = unique_values[0]
                    universal_code.append(f"# Universal assignment for column {col_idx} - applying to ALL rows")
                    universal_code.append(f"df.iloc[:, {col_idx}] = {value}")
                    universal_code.append("")
                else:
                    # Multiple values - analyze pattern and extend to full dataset
                    universal_code.append(f"# Pattern-based assignment for column {col_idx}")
                    
                    # Apply the specific transformations first
                    for row_idx, value in operations:
                        universal_code.append(f"if len(df) > {row_idx}:")
                        universal_code.append(f"    df.iloc[{row_idx}, {col_idx}] = {value}")
                    
                    # Extend pattern to rest of dataset
                    # Use the most common value for remaining rows
                    most_common_value = max(set(values), key=values.count)
                    max_transformed_row = max(op[0] for op in operations)
                    
                    universal_code.append(f"# Extend pattern to remaining rows (universal coverage)")
                    universal_code.append(f"for i in range({max_transformed_row + 1}, len(df)):")
                    universal_code.append(f"    if pd.isna(df.iloc[i, {col_idx}]) or df.iloc[i, {col_idx}] == '' or df.iloc[i, {col_idx}] is None:")
                    universal_code.append(f"        df.iloc[i, {col_idx}] = {most_common_value}")
                    universal_code.append("")
            
            # Add final validation to ensure no empty cells remain
            universal_code.extend([
                "# Final universal validation - ensure no empty cells remain",
                "for col_idx in range(len(df.columns)):",
                "    for row_idx in range(len(df)):",
                "        cell_value = df.iloc[row_idx, col_idx]",
                "        if pd.isna(cell_value) or cell_value == '' or cell_value is None:",
                "            # Fill with appropriate default based on column pattern",
                "            if col_idx < len(df.columns):",
                "                # Use the most common non-empty value in this column",
                "                non_empty_values = [v for v in df.iloc[:, col_idx] if not pd.isna(v) and v != '' and v is not None]",
                "                if non_empty_values:",
                "                    df.iloc[row_idx, col_idx] = non_empty_values[0]",
                "                else:",
                "                    df.iloc[row_idx, col_idx] = ''  # Fallback to empty string",
                "",
                "print(f'Universal transformation complete: {len(df)} rows, {len(df.columns)} columns processed')"
            ])
            
            # Insert universal code before the end of the script
            processed_lines.extend(universal_code)
        
        return '\n'.join(processed_lines)

    def _analyze_script_size_requirements(self, script: str) -> tuple[int, int]:
        """
        Analyze script to determine required DataFrame size
        
        Args:
            script: The script to analyze
            
        Returns:
            tuple[int, int]: (max_row_needed, max_col_needed)
        """
        max_row = 0
        max_col = 0
        
        # Pattern to find iloc operations
        iloc_pattern = re.compile(r'\.iloc\[(\d+),\s*(\d+)\]')
        
        for match in iloc_pattern.finditer(script):
            row_idx = int(match.group(1))
            col_idx = int(match.group(2))
            max_row = max(max_row, row_idx)
            max_col = max(max_col, col_idx)
        
        return max_row, max_col

    def _validate_script_universality(self, script: str) -> bool:
        """
        Validate if a script follows universal transformation patterns
        
        Args:
            script: The script to validate
            
        Returns:
            bool: True if script appears universal, False otherwise
        """
        # Check for hardcoded iloc operations
        hardcoded_iloc_pattern = re.compile(r'\.iloc\[\d+,\s*\d+\]\s*=')
        hardcoded_matches = hardcoded_iloc_pattern.findall(script)
        
        if len(hardcoded_matches) > 5:  # If too many hardcoded operations
            return False
        
        # Check for universal patterns
        universal_patterns = [
            r'df\[.*\]\s*=',  # Column assignment
            r'df\.loc\[.*,.*\]\s*=',  # Conditional assignment
            r'\.apply\(',  # Apply functions
            r'for.*in.*range\(len\(df\)\)',  # Loop over all rows
            r'df\.iloc\[:,.*\]\s*='  # Full column assignment
        ]
        
        universal_count = 0
        for pattern in universal_patterns:
            if re.search(pattern, script):
                universal_count += 1
        
        return universal_count > 0 or len(hardcoded_matches) == 0

    def _validate_result_completeness(self, original_df: pd.DataFrame, result_df: pd.DataFrame) -> None:
        """
        Validate that the result DataFrame is complete and properly populated
        
        Args:
            original_df: The original DataFrame
            result_df: The result DataFrame after transformation
            
        Raises:
            RuntimeError: If validation fails
        """
        # Check if result has reasonable size
        if len(result_df) < len(original_df) * 0.9:
            raise RuntimeError(
                f"Result has {len(result_df)} rows vs original {len(original_df)} rows. "
                f"The transformation may have lost data."
            )
        
        # Check for excessive empty cells
        empty_cells = result_df.isna().sum().sum() + (result_df == "").sum().sum()
        total_cells = result_df.shape[0] * result_df.shape[1]
        empty_percentage = (empty_cells / total_cells) * 100
        
        if empty_percentage > 50:  # More than 50% empty cells
            print(f"⚠️  WARNING: Result contains {empty_percentage:.1f}% empty cells")
        
        # Check if only the first few rows were modified (pattern detection)
        non_empty_rows = []
        for idx, row in result_df.iterrows():
            if not row.isna().all() and not (row == "").all():
                non_empty_rows.append(idx)
        
        if len(non_empty_rows) > 0:
            max_modified_row = max(non_empty_rows)
            if max_modified_row < len(result_df) * 0.1 and len(result_df) > 50:
                print(f"⚠️  WARNING: Data appears to be populated only in first {max_modified_row + 1} rows out of {len(result_df)} total rows")

    def _extend_transformation_to_full_dataset(self, result_df: pd.DataFrame, modified_cells: List[List[int]], original_row_count: int) -> tuple[pd.DataFrame, List[List[int]]]:
        """
        Extend partial transformations to cover the entire dataset
        
        Args:
            result_df: The partially transformed DataFrame
            modified_cells: List of modified cell coordinates
            original_row_count: Original number of rows
            
        Returns:
            tuple[pd.DataFrame, List[List[int]]]: Extended DataFrame and updated modified cells list
        """
        if not modified_cells:
            return result_df, modified_cells
        
        print("🔧 Extending partial transformation to cover entire dataset...")
        
        # Analyze the pattern of modifications
        col_patterns = {}
        
        for row_idx, col_idx in modified_cells:
            if col_idx not in col_patterns:
                col_patterns[col_idx] = {}
            
            cell_value = result_df.iloc[row_idx, col_idx]
            if row_idx not in col_patterns[col_idx]:
                col_patterns[col_idx][row_idx] = cell_value
        
        # Extend patterns to unmodified rows
        additional_modifications = []
        
        for col_idx, row_patterns in col_patterns.items():
            if not row_patterns:
                continue
            
            # Find the most common value in this column's transformations
            values = list(row_patterns.values())
            non_empty_values = [v for v in values if not pd.isna(v) and v != '' and v is not None]
            
            if non_empty_values:
                # Use the most frequent value as the pattern
                most_common_value = max(set(non_empty_values), key=non_empty_values.count)
                
                # Apply this value to all rows that haven't been modified
                modified_rows_in_col = set(row_idx for row_idx, c_idx in modified_cells if c_idx == col_idx)
                
                for row_idx in range(len(result_df)):
                    if row_idx not in modified_rows_in_col:
                        # Check if this cell is empty or needs updating
                        current_value = result_df.iloc[row_idx, col_idx]
                        if pd.isna(current_value) or current_value == '' or current_value is None:
                            result_df.iloc[row_idx, col_idx] = most_common_value
                            additional_modifications.append([row_idx, col_idx])
        
        # Update modified cells list
        all_modified_cells = modified_cells + additional_modifications
        
        print(f"✅ Extended transformation: added {len(additional_modifications)} additional cell modifications")
        
        return result_df, all_modified_cells
        
        # Extend patterns to unmodified rows
        additional_modifications = []
        
        for col_idx, row_patterns in col_patterns.items():
            if not row_patterns:
                continue
            
            # Find the most common value in this column's transformations
            values = list(row_patterns.values())
            non_empty_values = [v for v in values if not pd.isna(v) and v != '' and v is not None]
            
            if non_empty_values:
                # Use the most frequent value as the pattern
                most_common_value = max(set(non_empty_values), key=non_empty_values.count)
                
                # Apply this value to all rows that haven't been modified
                modified_rows_in_col = set(row_idx for row_idx, c_idx in modified_cells if c_idx == col_idx)
                
                for row_idx in range(len(result_df)):
                    if row_idx not in modified_rows_in_col:
                        # Check if this cell is empty or needs updating
                        current_value = result_df.iloc[row_idx, col_idx]
                        if pd.isna(current_value) or current_value == '' or current_value is None:
                            result_df.iloc[row_idx, col_idx] = most_common_value
                            additional_modifications.append([row_idx, col_idx])
        
        # Update modified cells list
        all_modified_cells = modified_cells + additional_modifications
        
        print(f"✅ Extended transformation: added {len(additional_modifications)} additional cell modifications")
        
        return result_df, all_modified_cells
