"""
Script Executor module
------------------
Safely executes Python scripts generated by the LLM
"""

import os
import pandas as pd
import numpy as np
import json
from typing import Tuple, List, Dict, Any, Optional, Hashable
from src.controller.security_manager import SecurityManager
from src.controller.script_manager import ScriptManager
from src.controller.file_manager import FileManager
from src.controller.schema_generator import SchemaGenerator

class ScriptExecutor:
    """
    Executes Python scripts generated by the LLM on spreadsheet data
    """
    
    def __init__(self, script_dir: Optional[str] = None):
        """
        Initialize the script executor
        
        Args:
            script_dir: Optional directory path for saving scripts
        """
        self.security_manager = SecurityManager()
        self.script_dir = script_dir or os.path.join('src', 'script')
        self.script_manager = ScriptManager(self.script_dir)
        self.schema_generator = SchemaGenerator()
    
    def execute_script(self, script: str, spreadsheet_df: pd.DataFrame, file_manager: Optional[FileManager] = None) -> Tuple[pd.DataFrame, List[List[int]]]:
        """
        Execute a Python script on spreadsheet data

        Args:
            script: The Python script generated by LLM
            spreadsheet_df: The pandas DataFrame containing spreadsheet data
            file_manager: Optional FileManager to save script for reference

        Returns:
            Tuple[pd.DataFrame, List[List[int]]]: Modified DataFrame and list of modified cells
        """
        print(f"\n{'='*60}")
        print("🔧 SCRIPT EXECUTION STARTING")
        print(f"{'='*60}")
        print("-" * 60)
        
        # Validate script for security
        if not self.security_manager.validate_script(script):
            error_msg = "Script validation failed due to security concerns. See server logs for details."
            print(f"❌ Security validation failed: {error_msg}")
            raise ValueError(error_msg)
        
        print("✓ Security validation passed")
        
        # Create a unique ID for this script
        import uuid
        script_id = str(uuid.uuid4())[:8]
        
        # Save script to src/script directory
        script_dir = self.script_dir
        os.makedirs(script_dir, exist_ok=True)
        script_path = os.path.join(script_dir, f"script_{script_id}.py")
        with open(script_path, 'w', encoding='utf-8') as f:
            f.write(script)
            
        print(f"💾 Script saved: {script_id}")
            
        # Save script metadata to json directory for reference if file_manager is provided
        if file_manager:
            file_manager.save_json_data({
                'script': script,
                'script_id': script_id,
                'timestamp': str(pd.Timestamp.now()),
                'columns': spreadsheet_df.columns.tolist(),
                'rows': len(spreadsheet_df)
            }, f"script_{script_id}")
            print(f"📊 Script metadata saved")
        
        # Track original data for determining modifications
        orig_columns = set(spreadsheet_df.columns)
        filled_df: pd.DataFrame = spreadsheet_df.copy().fillna(value=np.nan)
        data_dict: Dict[Hashable, Any] = filled_df.to_dict()
        orig_values = {str(k): v for k, v in data_dict.items()}
        
        print(f"📊 Original data: {spreadsheet_df.shape[0]} rows, {spreadsheet_df.shape[1]} columns")
        
        # Create a sandbox environment
        sandbox_globals = self._create_sandbox(spreadsheet_df)
        
        try:
            print("⚙️  Executing script...")
            
            # Check if script assigns to df at the end, if not add it
            script_lines = script.strip().split('\n')
            script_modifies_df = any('df =' in line or 'df=' in line for line in script_lines)
            
            # If script doesn't assign to df, we need to find the final result variable
            # Look for common result variable patterns that contain DataFrame operations
            result_vars = []
            for line in script_lines:
                if '=' in line and not line.strip().startswith('#'):
                    var_name = line.split('=')[0].strip()
                    if var_name and ('df' in var_name.lower() or 'transform' in var_name.lower() or 'result' in var_name.lower()):
                        # Check if it's a DataFrame assignment (not just a property access)
                        right_side = line.split('=', 1)[1].strip()
                        if any(keyword in right_side for keyword in ['DataFrame', '.copy()', 'apply_', 'pd.', 'df.']):
                            result_vars.append(var_name)
            
            # If we found a potential result variable, add assignment to df
            if not script_modifies_df and result_vars:
                final_var = result_vars[-1]  # Use the last one found
                script += f"\n\n# Auto-generated: Assign result back to df for system compatibility\ndf = {final_var}"
                print(f"🔧 Auto-patching script: Adding 'df = {final_var}' to ensure result is captured")
            
            # Execute script
            exec(script, sandbox_globals)

            # Get the modified dataframe
            modified_df = sandbox_globals.get('df', spreadsheet_df)

            # Reset the index to ensure consistent row numbering
            modified_df = modified_df.reset_index(drop=True)

            # Find modified cells
            modified_cells = self._find_modified_cells(
                orig_df=spreadsheet_df, 
                orig_columns=orig_columns,
                orig_values=orig_values, 
                new_df=modified_df
            )

            print(f"✅ Script executed successfully - {len(modified_cells)} cells modified")

            return modified_df, modified_cells
        except Exception as e:
            error_msg = str(e)
            print(f"❌ Script execution failed: {error_msg}")
            
            # --- PATCH: If error is 'iloc cannot enlarge its target object', try to expand DataFrame and warn ---
            if 'iloc cannot enlarge its target object' in error_msg:
                print("🔧 Attempting DataFrame patch for iloc enlargement error...")
                # Try to expand DataFrame by adding 10 extra rows and columns
                patched_df = spreadsheet_df.copy()
                extra_rows = 10
                extra_cols = 10
                for _ in range(extra_rows):
                    patched_df.loc[len(patched_df)] = [None] * len(patched_df.columns)
                for i in range(extra_cols):
                    patched_df[f'_extra_col_{i}'] = None
                try:
                    sandbox_globals = self._create_sandbox(patched_df)
                    exec(script, sandbox_globals)
                    modified_df = sandbox_globals.get('df', patched_df)
                    modified_df = modified_df.reset_index(drop=True)
                    modified_cells = self._find_modified_cells(
                        orig_df=spreadsheet_df, 
                        orig_columns=orig_columns,
                        orig_values=orig_values, 
                        new_df=modified_df
                    )
                    print("✅ Patched execution successful")
                    return modified_df, modified_cells
                except Exception as e2:
                    print(f"❌ Patched execution failed: {e2}")
                    raise RuntimeError(f"Script execution failed after patch: {e2}")
            # Return the original DataFrame without modifications instead of adding error column
            raise RuntimeError(f"Script execution failed: {error_msg}")
    
    def validate_script_safety(self, script: str) -> bool:
        """
        Validate that a script is safe to execute

        Args:
            script: The Python script to validate

        Returns:
            bool: True if the script is safe, False otherwise
        """
        return self.security_manager.validate_script(script)
    
    def _create_sandbox(self, df: pd.DataFrame) -> Dict[str, Any]:
        """
        Create a sandbox environment for script execution

        Args:
            df: The pandas DataFrame to operate on

        Returns:
            Dict[str, Any]: Dictionary of global variables for the sandbox
        """
        # Create a copy of the dataframe to avoid modifying the original
        sandbox_df = df.copy()
        
        # Define allowed modules and functions
        sandbox: Dict[str, Any] = {
            'df': sandbox_df,
            'pd': pd,
            'np': np,
            'print': print
        }
        
        return sandbox
    
    def _find_modified_cells(self, orig_df: pd.DataFrame, orig_columns: set[str], orig_values: Dict[str, Any], new_df: pd.DataFrame) -> List[List[int]]:
        """
        Find cells that were modified by the script

        Args:
            orig_df: Original DataFrame
            orig_columns: Set of original column names
            orig_values: Dict of original values
            new_df: Modified DataFrame

        Returns:
            List[List[int]]: List of [row, col] coordinates for modified cells
        """
        modified_cells: List[List[int]] = []
        
        # Check for new columns
        new_columns = set(new_df.columns) - orig_columns
        for col_name in new_columns:
            col_idx = list(new_df.columns).index(col_name)
            for row_idx in range(len(new_df)):
                modified_cells.append([row_idx, col_idx])
        
        # Check for modified values in existing columns
        for col_name in orig_columns:
            if col_name in new_df.columns:
                col_idx = list(new_df.columns).index(col_name)
                orig_col_idx = list(orig_df.columns).index(col_name)
                
                for row_idx in range(min(len(orig_df), len(new_df))):
                    # Check for equality considering NaN values
                    orig_val: Any = orig_df.iat[row_idx, orig_col_idx]
                    new_val: Any = new_df.iat[row_idx, col_idx]
                    
                    if pd.isna(orig_val) and pd.isna(new_val):
                        continue  # Both NaN, not modified
                    elif pd.isna(orig_val) or pd.isna(new_val):
                        # One is NaN and the other isn't, they're different
                        modified_cells.append([row_idx, col_idx])
                    elif orig_val != new_val:
                        # Both are non-NaN but have different values
                        modified_cells.append([row_idx, col_idx])
        
        return modified_cells
    
    def generate_schema_from_df(self, df: pd.DataFrame) -> Dict[str, Any]:
        """
        Generate a schema from the provided DataFrame
        
        Args:
            df: The pandas DataFrame to analyze
            
        Returns:
            Dict[str, Any]: JSON schema representing the structure
        """
        return self.schema_generator.generate_schema(df)
    
    def generate_transformation_script(self, source_df: pd.DataFrame, target_df: pd.DataFrame) -> str:
        """
        Generate a script to transform source_df to match the structure of target_df
        
        Args:
            source_df: The source DataFrame to transform
            target_df: The target DataFrame with the desired structure
            
        Returns:
            str: A prompt for the LLM to generate a transformation script
        """
        target_schema = self.schema_generator.generate_schema(target_df)
        return self.schema_generator.get_transformation_prompt(source_df, target_schema)

    def execute_universal_algorithm(self, script: str, spreadsheet_df: pd.DataFrame, file_manager: Optional[FileManager] = None) -> Tuple[pd.DataFrame, List[List[int]]]:
        """
        Execute a universal algorithm script on spreadsheet data with error handling and retry
        
        Args:
            script: The universal algorithm script generated by LLM
            spreadsheet_df: The pandas DataFrame containing spreadsheet data
            file_manager: Optional FileManager to save script for reference
            
        Returns:
            Tuple[pd.DataFrame, List[List[int]]]: Modified DataFrame and list of modified cells
        """
        print(f"\n{'='*60}")
        print("🚀 UNIVERSAL ALGORITHM EXECUTION STARTING")
        print(f"{'='*60}")
        
        try:
            result = self.execute_script(script, spreadsheet_df.copy(), file_manager)
            print(f"✅ Universal algorithm execution successful")
            return result
            
        except Exception as e:
            error_msg = str(e)
            print(f"❌ Universal algorithm execution failed: {error_msg}")
            # Store the error for potential retry
            self._last_error = error_msg
            raise e

    def execute_universal_algorithm_with_validation(self, script: str, spreadsheet_df: pd.DataFrame, file_manager: Optional[FileManager] = None) -> Tuple[pd.DataFrame, List[List[int]]]:
        """
        Execute a universal algorithm script with enhanced validation to ensure full dataset processing
        
        Args:
            script: The universal algorithm script generated by LLM
            spreadsheet_df: The pandas DataFrame containing spreadsheet data
            file_manager: Optional FileManager to save script for reference
            
        Returns:
            Tuple[pd.DataFrame, List[List[int]]]: Modified DataFrame and list of modified cells
            
        Raises:
            RuntimeError: If the algorithm appears to only process partial data
        """
        print(f"\n{'='*60}")
        print("UNIVERSAL ALGORITHM EXECUTION WITH VALIDATION STARTING")
        print(f"{'='*60}")
        
        original_row_count = len(spreadsheet_df)
        original_col_count = len(spreadsheet_df.columns)
        
        print(f"📊 Original dataset: {original_row_count} rows, {original_col_count} columns")
        
        try:
            # Execute the script
            result_df, modified_cells = self.execute_script(script, spreadsheet_df.copy(), file_manager)
            
            # Validate that the algorithm processed the full dataset
            result_row_count = len(result_df)
            result_col_count = len(result_df.columns)
            
            print(f"📈 Result dataset: {result_row_count} rows, {result_col_count} columns")
            
            # Check if the algorithm appears to have only processed a subset of data
            if result_row_count < original_row_count * 0.9:  # If result has less than 90% of original rows
                error_msg = (
                    f"VALIDATION FAILED: Algorithm appears to have only processed {result_row_count} rows "
                    f"out of {original_row_count} original rows. This suggests the algorithm is not "
                    f"processing the entire dataset as required. The algorithm should work on ALL rows "
                    f"in the DataFrame, not just a subset."
                )
                print(f"❌ VALIDATION FAILED: {error_msg}")
                raise RuntimeError(error_msg)
            
            # Additional validation: check if modifications seem limited to first few rows only
            if len(modified_cells) > 0:
                max_modified_row = max(cell[0] for cell in modified_cells)
                if max_modified_row < min(30, original_row_count * 0.5):  # If modifications only in first 30 rows or less than 50% of data
                    if original_row_count > 50:  # Only flag this for larger datasets
                        warning_msg = (
                            f"⚠️  Modifications appear limited to rows 0-{max_modified_row} "
                            f"out of {original_row_count} total rows. Algorithm may not be processing entire dataset."
                        )
                        print(f"{warning_msg}")
                        # Don't raise error for this, just warn, as some algorithms might legitimately only modify top rows
            
            print(f"✅ Algorithm validation successful: processed {result_row_count} rows")
            return result_df, modified_cells
            
        except Exception as e:
            error_msg = str(e)
            print(f"Algorithm execution/validation failed: {error_msg}")
            # Store the error for potential retry
            self._last_error = error_msg
            raise e

    def get_last_execution_error(self) -> str:
        """Get the last execution error for retry purposes"""
        return getattr(self, '_last_error', '')
