"""Manage storage and retrieval of LLM-generated Python scripts."""

import os, time, uuid
from datetime import datetime
from typing import Dict, Any, Optional

class ScriptManager:
    """Manage storage and retrieval of scripts generated by the LLM."""
    
    def __init__(self, script_dir: Optional[str] = None):
        """Initialize the script manager."""
        self.script_dir = script_dir or os.path.join('src', 'scripts')
        os.makedirs(self.script_dir, exist_ok=True)
    
    def save_script(self, script: str, metadata: Optional[Dict[str, Any]] = None) -> str:
        """Save a script and return its generated ID."""
        script_id = str(uuid.uuid4())[:8]
        ts_display = datetime.now().isoformat()
        ts_name = datetime.now().strftime("%d%m%Y%H%M%S")

        metadata_section = ""
        if metadata:
            metadata_section = f"\nMetadata: {metadata}"

        header = (
            "\"\"\"\n"
            f"Auto-generated script {script_id}\n"
            f"Generated on: {ts_display}{metadata_section}\n"
            "\"\"\"\n"
        )
        script_content = header + script + "\n"

        file_path = os.path.join(self.script_dir, f"{ts_name}_{script_id}.py")
        with open(file_path, 'w', encoding='utf-8') as f:
            f.write(script_content)

        return script_id
    
    def get_script(self, script_id: str) -> Optional[str]:
        """Get a script's content by ID if found, else None."""
        file_path = None
        try:
            for filename in os.listdir(self.script_dir):
                if filename.endswith(f"_{script_id}.py"):
                    file_path = os.path.join(self.script_dir, filename)
                    break
        except FileNotFoundError:
            return None
        if not file_path or not os.path.exists(file_path):
            return None
            
        with open(file_path, 'r', encoding='utf-8') as f:
            return f.read()
            
    def get_script_metadata(self, script_id: str) -> Optional[Dict[str, Any]]:
        """Extract metadata dict from a script's header if present."""
        script_content = self.get_script(script_id)
        if not script_content:
            return None
        
        try:
            lines = script_content.split('\n')
            for line in lines:
                if line.strip().startswith('Metadata:'):
                    metadata_str = line.strip()[10:]
                    import ast
                    return ast.literal_eval(metadata_str)
        except Exception:
            pass
        
        return None
        
    def list_scripts(self) -> Dict[str, str]:
        """List all available scripts as {script_id: path}."""
        scripts: Dict[str, str] = {}
        
        if not os.path.exists(self.script_dir):
            return scripts
            
        for filename in os.listdir(self.script_dir):
            if filename.endswith(".py") and filename != "__init__.py":
                base = filename[:-3]
                if "_" in base:
                    script_id = base.split("_")[-1]
                else:
                    script_id = base
                scripts[script_id] = os.path.join(self.script_dir, filename)
                
        return scripts
        
    def cleanup_old_scripts(self, max_age_hours: int = 24) -> int:
        """Delete script files older than max_age_hours; return count deleted."""
        
        now = time.time()
        max_age_seconds = max_age_hours * 3600
        deleted_count = 0
        
        if not os.path.exists(self.script_dir):
            return 0
            
        for filename in os.listdir(self.script_dir):
            if filename.endswith(".py") and filename != "__init__.py":
                file_path = os.path.join(self.script_dir, filename)
                if os.path.isfile(file_path) and now - os.path.getmtime(file_path) > max_age_seconds:
                    try:
                        os.remove(file_path)
                        deleted_count += 1
                    except (PermissionError, OSError) as e:
                        print(f"Warning: Could not delete script file {file_path}: {e}")
        
        return deleted_count

    def find_script_path(self, script_id: str) -> Optional[str]:
        """Find the full path of a script by its ID (supports timestamp prefix)."""
        if not os.path.exists(self.script_dir):
            return None
        for filename in os.listdir(self.script_dir):
            if filename.endswith(f"_{script_id}.py"):
                return os.path.join(self.script_dir, filename)
        return None
